//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by APIDemo.rc
//
#define IDD_APIDEMO_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_DLG_SUB_INIT                130
#define IDD_DLG_SUB_REAL                131
#define IDD_DLG_SUB_REMOTEREC           132
#define IDD_DLG_SUB_LOCALREC            133
#define IDD_DIALOG_MSG                  137
#define IDC_COMBO3                      1010
#define IDC_COMBO4                      1011
#define IDC_BUTTON_PAUSE                1012
#define IDC_BUTTON_GETVOL               1013
#define IDC_BUTTON_SETVOL               1014
#define IDC_EDIT_GETVOL                 1015
#define IDC_EDIT_GETVOL2                1016
#define IDC_BUTTON_AUDIOON              1016
#define IDC_BUTTON_AUDIOOFF             1017
#define IDC_BUTTON_AUDIOON2             1018
#define IDC_DATETIMEPICKER1             1019
#define IDC_BUTTON29                    1020
#define IDC_DATETIMEPICKER2             1020
#define IDC_BUTTON_PRESETLU             1021
#define IDC_DATETIMEPICKER3             1021
#define IDC_BUTTON30                    1022
#define IDC_DATETIMEPICKER4             1022
#define IDC_BUTTON_PRESETU              1023
#define IDC_DATETIMEPICKER5             1023
#define IDC_BUTTON31                    1024
#define IDC_DATETIMEPICKER6             1024
#define IDC_BUTTON_PRESETRU             1025
#define IDC_DATETIMEPICKER7             1025
#define IDC_BUTTON32                    1026
#define IDC_DATETIMEPICKER10            1026
#define IDC_DATETIMEPICKER8             1026
#define IDC_BUTTON_PRESETL              1027
#define IDC_BUTTON_AUDIOOFF2            1027
#define IDC_BUTTON33                    1028
#define IDC_BUTTON_SLOW                 1028
#define IDC_BUTTON_PRESET3D             1029
#define IDC_BUTTON_RAPID                1029
#define IDC_BUTTON34                    1030
#define IDC_BUTTON_                     1030
#define IDC_BUTTON_SPEEDPLAY            1030
#define IDC_BUTTON_PRESETR              1031
#define IDC_BUTTON35                    1032
#define IDC_BUTTON_PRESETLD             1033
#define IDC_BUTTON36                    1034
#define IDC_BUTTON_PRESETD              1035
#define IDC_BUTTON37                    1036
#define IDC_BUTTON_RD                   1037
#define IDC_BUTTON38                    1038
#define IDC_BUTTON_ZOOMIN               1039
#define IDC_BUTTON39                    1040
#define IDC_BUTTON40                    1041
#define IDC_BUTTON_PRESETGOTO           1042
#define IDC_BUTTON42                    1043
#define IDC_BUTTON_ZOOMOUT              1044
#define IDC_BUTTON_PRESETSET            1054
#define IDC_BUTTON41                    1055
#define IDC_BUTTON_PRESETDEL            1056
#define IDC_BUTTON43                    1057
#define IDC_BUTTON_PRESETCLE            1058
#define IDC_EDIT_MSG                    1059
#define IDC_EDIT_REC                    1060
#define IDC_COMBO_RECF                  1061
#define IDC_EDIT_PIC                    1062
#define IDC_COMBO_PICF                  1063
#define IDC_EDIT_CAMERAID               1064
#define IDC_COMBO_STREAMTYPE            1065
#define IDC_TAB_OPERATE                 1066
#define IDC_BUTTON_INIT                 1067
#define IDC_BUTTON_UNINIT               1068
#define IDC_BUTTON_LOGIN                1070
#define IDC_BUTTON_GETPFVER             1072
#define IDC_BUTTON_LOGOUT               1074
#define IDC_EDIT_IPADDR                 1076
#define IDC_BUTTON_SETDDCBF2            1078
#define IDC_EDIT_CAMID                  1081
#define IDC_EDIT_STREAMTYPE             1083
#define IDC_BUTTON_GETSDKVER            1084
#define IDC_BUTTON_STARTREAL            1085
#define IDC_EDIT_CAMIDT                 1086
#define IDC_BUTTON_STOPREAL             1088
#define IDC_EDIT_STARTTMT               1089
#define IDC_EDIT_ABITYPE                1090
#define IDC_SLIDER_SPEED                1091
#define IDC_EDIT_ENDTMP                 1092
#define IDC_STATIC_WND0                 1094
#define IDC_EDIT_STREAMURL              1095
#define IDC_BUTTON_GETPFABI             1096
#define IDC_STATIC_WND1                 1097
#define IDC_BUTTON_SRPLAYBYT            1098
#define IDC_STATIC_WND2                 1100
#define IDC_BUTTON_STOPSRP              1101
#define IDC_BUTTON_STOPPLAYB            1101
#define IDC_BUTTON_PRESETQ2             1102
#define IDC_STATIC_WND3                 1103
#define IDC_EDIT_ENDTMT                 1104
#define IDC_EDIT_PRESETNO               1106
#define IDC_EDIT_RECORDF                1107
#define IDC_BUTTON_RECFIND              1108
#define IDC_EDIT_RECPATH                1109
#define IDC_BUTTON_SRPBYF               1110
#define IDC_BUTTON_PLAYBACK             1110
#define IDC_BUTTON_STARTLREC            1111
#define IDC_STATIC_RPWND                1112
#define IDC_BUTTON_STOPLREC             1113
#define IDC_BUTTON_RPPAUSE              1114
#define IDC_EDIT_PICPATH                1115
#define IDC_BUTTON_RESUME               1115
#define IDC_BUTTON_RPPAUSE2             1115
#define IDC_BUTTON_RPSTOP               1116
#define IDC_BUTTON_PICCAPTURE           1117
#define IDC_BUTTON_RPFRAMEF             1118
#define IDC_EDIT_PICPATH2               1119
#define IDC_EDIT_PICFORMAT              1120
#define IDC_BUTTON_RPFRAMEB             1121
#define IDC_EDIT_SPEED                  1122
#define IDC_BUTTON_FORWARDP             1123
#define IDC_BUTTON_SPEED_2              1123
#define IDC_BUTTON_BACKP                1124
#define IDC_BUTTON_SPEED_1_2            1124
#define IDC_BUTTON_STARTDLBYT           1125
#define IDC_BUTTON_BACKP4               1125
#define IDC_BUTTON_DOWNLOAD             1125
#define IDC_EDIT_STREAMPOS              1126
#define IDC_BUTTON_BACKP8               1126
#define IDC_EDIT_CURRENTTIME            1126
#define IDC_BUTTON_STARTDLBYF           1127
#define IDC_BUTTON_BACKP16              1127
#define IDC_BUTTON_STOPDL               1128
#define IDC_BUTTON_BACKP1               1128
#define IDC_BUTTON_GETDLPOS             1129
#define IDC_EDIT_RECORDT                1130
#define IDC_EDIT_CAMIDP                 1131
#define IDC_EDIT_LOCATETIME             1131
#define IDC_EDIT_STARTTMP               1132
#define IDC_EDIT_RECORDURL              1133
#define IDC_BUTTON_STARTFRP             1134
#define IDC_BUTTON_FORWARDP3            1134
#define IDC_BUTTON_SPEED_4              1134
#define IDC_EDIT_PICPATH3               1135
#define IDC_BUTTON_STOPFRP              1136
#define IDC_BUTTON_FORWARDP5            1136
#define IDC_BUTTON_SPEED_8              1136
#define IDC_BUTTON_PICCAPTURE2          1137
#define IDC_BUTTON_GETFRPPOS            1138
#define IDC_BUTTON_FORWARDP6            1138
#define IDC_BUTTON_SPEED_16             1138
#define IDC_EDIT_PICFORMAT2             1139
#define IDC_BUTTON_GETTOTALTM           1140
#define IDC_BUTTON_SETRPPOS             1141
#define IDC_EDIT_RECORDPATH             1142
#define IDC_BUTTON_BACKP3               1142
#define IDC_BUTTON_SPEED_1_4            1142
#define IDC_EDIT_POSTIME                1143
#define IDC_BUTTON_BACKP5               1143
#define IDC_BUTTON_SPEED_1_8            1143
#define IDC_EDIT_SOURCEFILE             1144
#define IDC_BUTTON_BACKP6               1144
#define IDC_BUTTON_SPEED_1_16           1144
#define IDC_EDIT_DESTINATIONFILE        1145
#define IDC_EDIT_STARTTMCUT             1146
#define IDC_EDIT_ENDTMCUT               1147
#define IDC_BUTTON_FORWARDP7            1147
#define IDC_BUTTON_SPEED_1              1147
#define IDC_BUTTON_FILECUT              1148
#define IDC_BUTTON_BACKP7               1148
#define IDC_EDIT_PICPATH4               1150
#define IDC_BUTTON_PICCAPTURE3          1151
#define IDC_EDIT_PICFORMAT3             1153
#define IDC_LIST1                       1156
#define IDC_EDIT1                       1159
#define IDC_EDIT2                       1161
#define IDC_EDIT_MAXSIZE                1161
#define IDC_EDIT_SETVOL                 1161
#define IDC_STATIC_MSG                  1162
#define IDC_EDIT_SETVOL2                1162
#define IDC_EDIT3                       1163
#define IDC_BUTTON_GPOS                 1164
#define IDC_BUTTON_GETCURRENTTIME       1164
#define IDC_BUTTON_SPOS                 1165
#define IDC_BUTTON_LOCATEPLAY           1165
#define IDC_CHECK1                      3001
#define IDC_EDIT_NAME                   3002
#define IDC_CHECK2                      3002
#define IDC_EDIT_PORT                   3003
#define IDC_CHECK_SOUNDCTRL             3003
#define IDC_BUTTON_FORWARDP2            3004
#define IDC_EDIT_USER                   3005
#define IDC_BUTTON_FORWARDP4            3006
#define IDC_EDIT_PWD                    3007
#define IDC_BUTTON_FORWARDP8            3008
#define IDC_BUTTON_FORWARDP16           3011
#define IDC_BUTTON6                     3012
#define IDC_BUTTON_BACKP2               3013
#define IDC_BUTTON8                     3014
#define IDC_BUTTON_FORWARDP1            3015
#define IDC_BUTTON7                     3016
#define IDC_COMBO1                      3017
#define IDC_COMBO2                      3018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
